# Change baseurl before deploy
baseURL = "https://mjohnson7cd.github.io/thesneers/"
languageCode = "en-us"
title = "The Sneers"
defaultContentLanguage = "en"
hasCJKLanguage = false
relativeURLs = false
canonifyURLs = true

[params]
description = "The Sneers - Official Band Website"
ShowReadingTime = false
ShowPostNavLinks = false
ShowShareButtons = false

[params.author]
name = "The Sneers"
email = ""

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/artist/1BuwrPJoNGJoylPEbyaYUI"
[[params.socialIcons]]
name = "applemusic"
url = "https://music.apple.com/us/artist/the-sneers/1772566348"
[[params.socialIcons]]
name = "bandcamp"
url = "https://thesneers.bandcamp.com/"
[[params.socialIcons]]
name = "youtubemusic"
url = "https://music.youtube.com/channel/UC3xLzfBcobGIAukqKcNMU9Q"

[pagination]
pagerSize = 5


[caches]
[caches.images]
dir = ':cacheDir/images'