# Configure main menu and social menu
[[main]]
identifier = "artwork"
name = "Artwork"
url = "/photos/"
[main.params]
icon = "photo-scan"
newtab = false

[[social]]
identifier = "Spotify"
name = "spotify"
url = "https://open.spotify.com/artist/1BuwrPJoNGJoylPEbyaYUI"

[social.params]
icon = "brand-spotify"

[[social]]
identifier = "applemusic"
name = "Apple Music"
url = "https://music.apple.com/us/artist/the-sneers/1772566348"

[social.params]
icon = "brand-apple"
#
#[[social]]
#identifier = "youtubemusic"
#name = "YouTube Music"
#url = "https://music.youtube.com/channel/UC3xLzfBcobGIAukqKcNMU9Q"
#
#[social.params]
#icon = "brand-youtube"
#
#
[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/thesneers/?hl=en"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "bandcamp"
name = "Bandcamp"
url = "https://thesneers.bandcamp.com/"

[social.params]
icon = "brand-bandcamp"
