# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "spotify"
name = "spotify"
url = "https://open.spotify.com/artist/1BuwrPJoNGJoylPEbyaYUI"

[social.params]
icon = "brand-spotify"

[[social]]
identifier = "applemusic"
name = "Apple Music"
url = "https://music.apple.com/us/artist/the-sneers/1772566348"

[social.params]
icon = "brand-apple"
#
#[[social]]
#identifier = "youtubemusic"
#name = "YouTube Music"
#url = "https://music.youtube.com/channel/UC3xLzfBcobGIAukqKcNMU9Q"
#
#[social.params]
#icon = "brand-youtube"
#
#
[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/thesneers/?hl=en"

[social.params]
icon = "brand-instagram"
